---
baseURL: https://jdillon.github.io/dionysus-example/
languageCode: en-us
title: Hugo Dionysus Theme Example
theme: dionysus

# Publish content to maven-standard-ish location for generated content
publishdir: ../../../target/hugo-public

params:
  inceptionYear: 2018

taxonomies:
  tag: tags
  category: categories

# Blackfriday options; see https://gohugo.io/content-management/formats/

# see https://www.webpagefx.com/tools/emoji-cheat-sheet/
enableEmoji: true

# Highlight options; see https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences: true

# see https://xyproto.github.io/splash/docs/all.html
pygmentsStyle: manni
